#!/usr/bin/env bash
# Generates src/stubs.c from the wit-bindgen-generated openssl.h.
#
# For every exported function that isn't already implemented in
# src/component.c (tracked via weak references below), emit a stub body
# that:
#   - for bool fallible fns (err out-param): sets err.tag = _INTERNAL,
#     err.val.internal = 0, and returns false
#   - for bool non-fallible fns: returns false
#   - for void fns: no-op
#   - for resource-returning fns: abort() — unimplemented
#   - for _destructor fns: no-op (we don't attach reps yet)
#
# This file is regenerated by `make bindings`; edits here are lost.

set -euo pipefail

HDR="${1:-src/bindings/openssl.h}"
# Second arg can be a single file or whitespace-separated list of files.
IMPL_FILES="${2:-src/component.c}"
OUT="${3:-src/stubs.c}"

if [ ! -f "$HDR" ]; then
  echo "gen-stubs: $HDR not found; run wit-bindgen first" >&2
  exit 1
fi

IMPL_SYMS=$(cat $IMPL_FILES 2>/dev/null | \
            grep -oE 'exports_openssl_component_[a-zA-Z0-9_]+' | sort -u || true)

cat > "$OUT" <<'EOF'
// Auto-generated by scripts/gen-stubs.sh — DO NOT EDIT.
//
// Stubs for every WIT export not yet implemented in component.c.
// Each stub reports an `internal(0)` error so callers see a coherent
// failure rather than a trap.

#include "bindings/openssl.h"
#include <stdlib.h>
#include <string.h>

EOF

# Extract exported function declarations (exclude `extern` imports).
grep -E '^(void|bool|[a-z_][a-zA-Z0-9_]+_t) +exports_openssl_component_[a-zA-Z0-9_]+\(' "$HDR" | \
while IFS= read -r decl; do
  sym=$(echo "$decl" | grep -oE 'exports_openssl_component_[a-zA-Z0-9_]+' | head -1)
  # Skip wit-bindgen-provided helpers (*_free); they're defined in openssl.c.
  case "$sym" in
    *_free) continue ;;
  esac
  if echo "$IMPL_SYMS" | grep -qx "$sym"; then
    continue
  fi
  ret=$(echo "$decl" | sed -E 's/^([a-zA-Z0-9_]+( \*)*).*/\1/')
  proto=$(echo "$decl" | sed -E 's/;[[:space:]]*$//')

  echo "$proto {"

  # Destructors: no-op.
  if [[ "$sym" == *_destructor ]]; then
    echo "  (void)rep;"
    echo "}"; echo
    continue
  fi

  # Figure out whether there's an `err` out-param of a *_error_t kind.
  err_type=$(echo "$decl" | grep -oE 'exports_openssl_component_[a-z_]+_[a-z_]+_error_t \*err' | awk '{print $1}' | head -1 || true)

  case "$ret" in
    void)
      # If there's a single out-ptr, zero it.
      outp=$(echo "$decl" | grep -oE '[a-zA-Z_][a-zA-Z0-9_]* \*ret' | awk '{print $1}' | head -1 || true)
      if [ -n "$outp" ]; then
        echo "  memset(ret, 0, sizeof(*ret));"
      fi
      ;;
    bool)
      if [ -n "$err_type" ]; then
        # Pick the tag name; by convention the stubs use `*_INTERNAL`
        # plus a `u.internal` / `val.internal` payload. wit-bindgen-c
        # names the tag fields distinctively per variant; we use the
        # uppercased last path component.
        tag_prefix=$(echo "$err_type" | sed -E 's/_t$//' | tr '[:lower:]' '[:upper:]')
        echo "  err->tag = ${tag_prefix}_INTERNAL;"
        echo "  err->val.internal = 0;"
      fi
      echo "  return false;"
      ;;
    *_own_*_t|exports_*_own_*_t)
      # Resource handles: no sensible zero value; abort.
      echo "  abort();"
      ;;
    *)
      # Fall-back scalar: zero.
      case "$ret" in
        uint8_t|uint16_t|uint32_t|uint64_t|int8_t|int16_t|int32_t|int64_t|size_t|float|double)
          echo "  return 0;"
          ;;
        *)
          echo "  (void)0; abort();"
          ;;
      esac
      ;;
  esac

  echo "}"
  echo
done >> "$OUT"

echo "gen-stubs: wrote $OUT"
